export enum DocumentCategory {
  OEM_MANUAL = "OEM_MANUAL",
  SOP = "SOP",
  PID_DRAWING = "PID_DRAWING",
  MAINTENANCE_WORK_ORDER = "MAINTENANCE_WORK_ORDER",
  REGULATORY_AUDIT = "REGULATORY_AUDIT",
  UNKNOWN = "UNKNOWN"
}

export enum AssetCriticality {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW"
}

export enum AlertSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  ERROR = "ERROR",
  CRITICAL = "CRITICAL"
}

export enum SubBrainName {
  KNOWLEDGE = "KNOWLEDGE",
  MAINTENANCE = "MAINTENANCE",
  COMPLIANCE = "COMPLIANCE",
  RCA = "RCA",
  LESSONS_LEARNED = "LESSONS_LEARNED"
}

export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  INFERENCE_ERROR = "INFERENCE_ERROR"
}
